name: Format Prettier WorkFlow

on:
    push:
        branches:
            - "*"
            # - "!main"
    pull_request:
        paths:
            - "**.js"
            - "**.jsx"
            - "**.css"

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Install
              run: yarn install
              env:
                  CI: true

            - name: Run prettier
              run: yarn run prettier --write 'src/**/*.{js,jsx,css}'

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply prettier changes
